
version: '3'

services:
  todo-app-mysql:
    image: uportal/todo-app:latest
    container_name: todoapp-on-postgres-16
    restart: always
    environment:
      APP_NAME: Todo App with MySQL
      ACTIVE_PROFILES: dev,postgres
      APP_URL: http://localhost:8080
      APP_DB_HOST: postgresdb16-todoapp
      APP_DB_PORT: 5432
      APP_DB_NAME: db
      APP_DB_SCHEMA: todoapp
      APP_DB_USERNAME: todoapp-user
      APP_DB_PASSWORD: todoapp
    ports:
      - 8080:8080
    depends_on:
      todo-postgres16:
        condition: service_healthy

  todo-adminer:
    image: adminer:4.17.1
    container_name: adminer-todoapp
    restart: always
    ports:
      - 9090:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb16-todoapp
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: db
    depends_on:
      todo-postgres16:
        condition: service_healthy

  todo-postgres16:
    image: postgres:16
    container_name: postgresdb16-todoapp
    restart: always
    environment:
      POSTGRES_PASSWORD: "todoapp"
      POSTGRES_USER: "todoapp-user"
      POSTGRES_DB: "db"
      POSTGRES_SCHEMA: "todoapp"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
    ports:
      # <Port exposed> : < MySQL Port running inside container>, host port for using with mysql-workbench or dbeaver
      - '54321:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - dbpostgres16-todoapp:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 15

# Names our volume
volumes:
  dbpostgres16-todoapp:
