

services:
  todo-app-mariadb11:
    image: uportal/todo-app:latest
    container_name: todoapp-on-mariadb11
    restart: unless-stopped
    environment:
      APP_NAME: Todo App with MariaDB 11
      ACTIVE_PROFILES: dev,mariadb
      APP_URL: http://localhost:8080
      APP_DB_HOST: todoapp-mariadb11-db
      APP_DB_PORT: 3306
      APP_DB_NAME: db
      APP_DB_USERNAME: root
      APP_DB_PASSWORD: todoapp
      LOKI_URL: http://localhost:3100/loki/api/v1/push
      LOKI_ENABLED: false
    ports:
      - 8080:8080
    depends_on:
      todo-dbmariadb11:
        condition: service_healthy

  todo-adminer-mariadb11:
    image: adminer:4.17.1
    container_name: todoapp-adminer-on-mariadb11
    restart: unless-stopped
    ports:
      - 9090:8080
    environment:
      ADMINER_DEFAULT_SERVER: todoapp-mariadb11-db
    depends_on:
      todo-dbmariadb11:
        condition: service_healthy

  todo-dbmariadb11:
    platform: linux/amd64
    image: mariadb:11.7.2-ubi
    container_name: todoapp-mariadb11-db
    # command: /usr/sbin/mariadbd --mysql-native-password=ON
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MARIADB_USER: 'user'
      # You can use whatever password you like
      MARIADB_PASSWORD: 'todoapp'
      # Password for root access
      MARIADB_ROOT_PASSWORD: 'todoapp'
    ports:
      # <Port exposed> : < MySQL Port running inside container>, host port for using with mysql-workbench or dbeaver
      - '33067:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mariadb11-todoappdb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
# Names our volume
volumes:
  mariadb11-todoappdb:
