
version: '3'

services:
  todo-app-mysql:
    image: uportal/todo-app:latest

    restart: always
    environment:
      APP_NAME: Todo App with MySQL
      ACTIVE_PROFILES: dev,mysql
      APP_URL: http://localhost:8080
      APP_DB_HOST: dbmysql84
      APP_DB_PORT: 3306
      APP_DB_NAME: db
      APP_DB_USERNAME: root
      APP_DB_PASSWORD: todoapp
    ports:
      - 8080:8080
    depends_on:
      - todo-dbmysql84

  todo-adminer:
    image: adminer:4.8.1
    container_name: adminer-todoapp
    restart: always
    ports:
      - 9090:8080
    environment:
      ADMINER_DEFAULT_SERVER: dbmysql84
    depends_on:
      - todo-dbmysql84

  todo-dbmysql84:
    image: mysql:8.4.4
    container_name: dbmysql84
    command: mysqld --mysql-native-password=ON
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'todoapp'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'todoapp'
    ports:
      # <Port exposed> : < MySQL Port running inside container>, host port for using with mysql-workbench or dbeaver
      - '33066:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - dbmysql84-todoappdb:/var/lib/mysql

# Names our volume
volumes:
  dbmysql84-todoappdb:
