networks:
  proxy:
    external: true

services:
  todo-app-h2:
    image: uportal/todo-app:latest
    container_name: todoapp-on-h2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-h2.rule=Host(`todo-h2.example.com`)" # change hostname!
      - "traefik.http.routers.todo-h2.tls=true"
      - "traefik.http.routers.todo-h2.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.todo-h2.entrypoints=websecure"
      - "traefik.http.services.todo-h2.loadbalancer.server.port=8080"
    restart: unless-stopped
    networks:
      - proxy
    environment:
      APP_NAME: Todo Rest with Spring Boot and H2
      ACTIVE_PROFILES: dev,h2
      APP_URL: https://todo-h2.example.com # change hostname!
      LOKI_URL: http://localhost:3100/loki/api/v1/push
      LOKI_ENABLED: false
