networks:
  proxy:
    external: true

services:

  # whoami example container
  whoami:
    image: traefik/whoami:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)" # change hostname!
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.whoami.middlewares=secHeaders@file"
      - "traefik.http.services.whoami.loadbalancer.server.port=80" # set port the container listenes to
    networks:
      - proxy